# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: estimator_test
      
    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - restore_cache:
        keys:
          - build
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
      - save_cache:
          key: build
          paths:
            - _build
            - deps
            - ~/.mix
