# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: estimator_test
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - restore_cache:
          keys:
            - build-{{ checksum "mix.lock" }}
      - run: MIX_ENV=test mix local.rebar --force
      - run: MIX_ENV=test mix local.hex --force
      - run: MIX_ENV=test mix deps.get --only test
      - run: MIX_ENV=test mix ecto.create
      - run: MIX_ENV=test mix test
      - run: MIX_ENV=test mix archive.install hex sobelow --force
      - run: MIX_ENV=test mix sobelow --exit Low --verbose --ignore Config.HTTPS -i Config.CSP
      - store_test_results:
          path: /tmp/
      - save_cache:
          key: build-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
