# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.4
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: estimator_test
          MIX_ENV: test
      
    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - restore_cache:
          keys:
            - build
      - run: MIX_ENV=test mix local.rebar --force
      - run: MIX_ENV=test mix local.hex --force
      - run: MIX_ENV=test mix deps.get --only test
      - run: MIX_ENV=test mix ecto.create
      - run: MIX_ENV=test mix test
      - save_cache:
          key: build
          paths:
            - _build
            - deps
            - ~/.mix
